AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:bK9SyI3CDKScjURyBz9ngcd7ezPy,iv:XIigxr3bwfOABS01Z9rHUsVArRzR47MVWzBo+Le2LFM=,tag:VszLVaKsACwpD24vvcE0RQ==,type:str]
AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:5ypRtINb6jnEctJNGKd9,iv:bZOIjW78lxfBpi+8qxFnwl8hlYVWUADwh/QVkbD1Pg4=,tag:bA4gHNjfHCYk5IgsAIfQNg==,type:str]
AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:BaM1dbb3akpgwtLVOmpwA65PVOoUyvNMSvmHhOJdYGon9q7d,iv:j+F/dnibr6UDW6ZtYP0oPNqrb+/weusvVydCCGHsXvM=,tag:Kxe0ak8F6WAa+lrbR1zCjA==,type:str]
AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:fszd,iv:kFiqRGmNE+//DXv6Ut13Mdpg6c0Osp4Qsv+j3A1LC2Q=,tag:pxbOLrFZ5N0PIR15MxhZzQ==,type:str]
AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:Ou4=,iv:TYhJ4IcV/sjC1hdqV3aQKKl84r4iMOa6ZP+nLERsogs=,tag:HXB8Eago07VhUaEbUZLPUw==,type:str]
AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:grA2Da2n,iv:Ufh62Z4Q1lNHyPgik2CNimyPrbakRIJEx7VMMIBgZJo=,tag:hyOm9KByjp/j5fTWpYldMQ==,type:str]
AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:lInirj8=,iv:3QD9ix5YFX5ur8ogL8IvEwi+22qp8xb17KWLOAJYAnc=,tag:FIli+nnVHuOqm5jIIpAgpQ==,type:str]
AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:75WLXg==,iv:dPn9paiPkF0SFqODazZvK4xBKf7FNcm1TlQIM4y4sX8=,tag:0QeJrdq5wtmgsRIhvgVWnw==,type:str]
AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:kVbrGZwoZrIShaz7gK/VP2OIX5hiBGjvbPzWxn0gd6SntDwNCPZU7OMyHcn+Nw==,iv:xJF1HDfSiCXFeoK6bgFJY4q/9p2SnEHTgwreW3YibOU=,tag:sqh4VmkCE5MYG4HUnEOCrw==,type:str]
AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:padCMtAOmVAI7l8EK4EHJE5XUGRLITHMm2XdOSwbUys=,iv:tX0dUzYaPCSFZecEXDISGHSRB26ucgPEsyS7i5zLS50=,tag:dkqYRoNbsQam85Z/RQrqwA==,type:str]
AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:wP5c6oS05yG5d3iUKWDFJsIxlqjZ0ffEGCSXttxYAnlqyq6WVymzlLSV2Ds=,iv:JxLI48T+arecmZzfnIr58fnvWEg4RAaF73z0PfgJPjw=,tag:RUaz39tJesCtwyz07SusxQ==,type:str]
AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:zw/vVAY69awnvkbBYANhZhPlvsGYSiJHkEAPds+WdXgRnDua3fp/BDYhwx0M1wxsMQ2Y1k6P2fReLqSn6vq/7Q==,iv:JV7KOQYOWp/qNMXev6kmCH20u29pHw/v5h/1Fg8nn9s=,tag:HsE8fc1gaaEyQd3pQFHBXQ==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQkZON0g4blR6UEpSSHJr
        QTEyMzRtbGdaMDJWRy95ZTcxQ2U1UDhUS3hVCnN6UDI3M0o2dFhtOXMzcjlCSzYx
        OHlwbmYzRGxjT1hiNlRvbDVpVmZNTG8KLS0tIGc2OGtGb091MlI5UDBUdENVWTJl
        cXo2V2NMcmpsQlVvVnVETHZQOEltR1UKsk6/HrZnlAmPGrnQWiynQ2HuFrzliTOW
        3DeFZhSmaAg45My0Exm2/OVVFz+e5L+MFROAE2K+cPlhIOXaWGjdNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T13:35:09Z"
  mac: ENC[AES256_GCM,data:3eQ3K86UYnnr9gPZKTDl0TplsyM8J3eaNAys8QhOjZzepD2ArRSv7M9G6nahVJ5OrCO/DVYbErbDKVFX9Yv26u3FpE8NvcvpujRMjcKI2yAdW4JG0KnIuAPkcnevyGWc0CKEarUw2wRrXSpZuuQgdQ1FwhWYDAxrOM6vTNnxdxE=,iv:GRfKpSORdtLITp6QK3Ny6guHbbo5bjYWv4avIIHY6+g=,tag:Dd2PmalcEedFKV/4fx/oOg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
