name: mlflow
containers:
  - name: mlflow
    repository: ghcr.io/kahnwong/docker-mlflow
    tag: 0f88447
    port: 8080
    envFrom:
      - secretRef:
          name: mlflow
    env:
      - name: MLFLOW_DISABLE_TELEMETRY
        value: "true"
