kind: Deployment
name: mlflow
replicaCount: 1
kubeGreen: true
containers:
  - name: mlflow
    repository: ghcr.io/kahnwong/docker-mlflow
    tag: 82d5ca1
    port: 8080
    envFrom:
      - secretRef:
          name: mlflow
    env:
      - name: MLFLOW_DISABLE_TELEMETRY
        value: "true"
service:
  port: 8080
  nodePort: 30037
