kind: Deployment
name: trmnl
replicaCount: 1
containers:
  - name: trmnl
    repository: ghcr.io/kahnwong/trmnl-beszel
    tag: 3d4c549
    port: 3000
    env:
      - name: LOG_LEVEL
        value: error
    envFrom:
      - secretRef:
          name: trmnl
    volumeMounts:
      - name: data
        mountPath: /data
volumes:
  - name: data
    hostPath:
      path: /opt/trmnl/data
service:
  port: 3000
  nodePort: 30086
imagePullSecrets:
  - name: ghcr-cfg
