kind: Deployment
name: ory-hydra
replicaCount: 1
containers:
  - name: ory-hydra
    repository: ghcr.io/kahnwong/docker-excalidraw
    tag: latest
    port: 3002
service:
  port: 3002
#  nodePort: 30038
