- name: Compose upgrade
  hosts: "{{ host | mandatory }}"
  tasks:
    - name: Pull, recreate, and start compose target
      ansible.builtin.shell: |
        cd self-hosted/docker && \
        docker compose -f compose-{{ inventory_hostname }}.yaml pull && \
        docker compose -f compose-{{ inventory_hostname }}.yaml down && \
        docker compose -f compose-{{ inventory_hostname }}.yaml up -d
