POSTGRES_USER: ENC[AES256_GCM,data:exF9JSmh75kA,iv:Ske3ZAo6ZZ7d7/8Yver8GEqtsx+iAfD2a2JXjghJsOI=,tag:k/vae+RXULWwRfuklkGO2Q==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:PmJ16nOTKn5YHAsdcTJ7QtVsOAZm0Rg4BbA2IkHnW3Y=,iv:3RqY9vKIbaSMBjJ0Nt7s19hpYevzbRR8g0/vNUXWP+s=,tag:7IYE1jEVV0K0iSNIBbLtCA==,type:str]
POSTGRES_DB: ENC[AES256_GCM,data:njn+hcrF5/Ql,iv:rMnC26xJ9Hj+HPqmuqmuvMEkbDWyXMUBHW85eKw4aaQ=,tag:Yxg6pp9yYlpVlzdRqscEVg==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmt2aHlwU3YwcURsSGl5
        SG1uek10QlFiMFZmRFJubkdqT1B0QU1TekJ3CkJmb3I5WUppOTEvb1hoSUpsUlZq
        Rkloc2pNSitybVZrZExVSFdycExIcWcKLS0tIE1nSVhWNWFiTUZzOXh5MGlTOFd5
        bVNlQzNlYUpiNDc1RDFhcXc1N09LcTAKu8J/+XManXl0vrwcSXUm8WWFk1D6pwiD
        ampWsLlMxeR2GEGyEP+LSE/D9dytzhk9ghEOJQch/mrra3JAeWr/KQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T13:33:00Z"
  mac: ENC[AES256_GCM,data:1wYjoSunbRUh7uqCZofgxeVvLHD+CuYQdMI5zvDjhAaP8bJ+4PVLRzYNXsBwkAGKEt4zzV0+7yCWSsSNfjoonz/NATGeCqxHtoTEOeIHjlDbKn1NhxOQ8rqHQhDWT/27SxHJfvBnvu5WZi3+7y0jAH6WwQfLG8bbB6ORju+Jtgo=,iv:C1x0BgyQr4cE6OddDLkhQr7fMQb438iltS+qI0MXPMs=,tag:zCdTkm9Um4+3VniKXbS4uA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
