all:
  hosts:
    nuc:
      ansible_host: nuc
    argon:
      ansible_host: argon
    gcp-lab:
      ansible_host: gcp-lab
    oracle-lab:
      ansible_host: oracle-lab
    oracle-lab2:
      ansible_host: oracle-lab2
