services:
  # required oauth permissions: keys.auth-keys write
  tailscale-warpgate:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:warpgate
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    env_file:
      - .warpgate.env
    volumes:
      - /opt/tailscale/tailscale-warpgate/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  warpgate:
    image: ghcr.io/warp-tech/warpgate:0.14
    ports:
      - 2222:2222 # ssh
      - 8888:8888 # http
      - 33306:33306 # mysql
      - 55432:55432 # postgres
    volumes:
      - /opt/warpgate/data:/data
    stdin_open: true
    tty: true
    depends_on:
      - tailscale-warpgate
    network_mode: service:tailscale-warpgate
