services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.18.7
    # ports:
    #   - "8090:8090"
    environment:
      - APP_URL=https://beszel.karnwong.me
    volumes:
      - /opt/beszel/data:/beszel_data
      - /opt/beszel/socket:/beszel_socket
    restart: always
  gatus:
    container_name: gatus
    restart: always
    ports:
      - "8080:8080"
    image: twinproduction/gatus:v5.36.0
    volumes:
      - ./config/gatus.yaml:/config/config.yaml:ro
      - /opt/gatus/data:/data
  # ---- caddy ----
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.oracle2:/etc/caddy/Caddyfile:ro
      - /opt/caddy/data:/data
