services:
  picoshare:
    image: "mtlynch/picoshare:v1.5.4"
    container_name: picoshare
    restart: always
    env_file:
      - .env.app.picoshare
    volumes:
      - /opt/picoshare/data:/data
      # ports:
      #  - "4001:4001"
  iroh-relay:
    container_name: iroh-relay
    restart: always
    # ports:
    #  - 81:80
    image: n0computer/iroh-relay:v1.1.0
    environment:
      - RUST_LOG=info
    command: ["-c", "/config/relay.toml"]
    volumes:
      - ./config/iroh-relay.toml:/config/iroh-relay.toml:ro
  memos:
    # prune archived notes
    # `DELETE FROM memo WHERE row_status = 'ARCHIVED'; VACUUM;`
    # prune assets
    # `DELETE FROM attachment WHERE memo_id IS NOT NULL AND memo_id NOT IN (SELECT id FROM memo); VACUUM;`
    container_name: memos
    restart: always
    # ports:
    #  - 5230:5230
    image: neosmemo/memos:0.30.0
    environment:
      - MEMOS_INSTANCE_URL=https://memos.karnwong.me
    volumes:
      - /opt/memos/data:/var/opt/memos
  # ---- caddy ----
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.oracle:/etc/caddy/Caddyfile:ro
      - /opt/caddy/data:/data
