services:
  anisette:
    container_name: anisette
    restart: always
    # ports:
    #  - 6969:6969
    image: dadoum/anisette-v3-server
    volumes: # `sudo chown -R 1000:1000 /opt/anisette`
      - /opt/anisette/data:/home/Alcoholic/.config/anisette-v3/lib
    user: "1000:1000"
  iroh-relay:
    container_name: iroh-relay
    restart: always
    # ports:
    #  - 81:80
    image: n0computer/iroh-relay:v0.96.1
    environment:
      - RUST_LOG=info
    command: ["-c", "/config/relay.toml"]
    volumes:
      - ./config/iroh-relay.toml:/config/iroh-relay.toml:ro
  gatus:
    container_name: gatus
    restart: always
    # ports:
    #  - 8080:8080
    image: twinproduction/gatus:v5.35.0
    volumes:
      - ./config/gatus.yaml:/config/config.yaml:ro
      - /opt/gatus/data:/data
  vaultwarden:
    image: vaultwarden/server:1.35.3
    container_name: vaultwarden
    restart: always
    env_file:
      - .env.app.vaultwarden
    volumes:
      - /opt/vaultwarden/data:/data
  ontime:
    container_name: ontime
    image: getontime/ontime:v4
    ports:
      - "4001:4001/tcp" # web & api
      - "8888:8888/udp" # OSC input
      - "9999:9999/udp" # OSC output
    volumes:
      - /opt/ontime/data:/data
    environment:
      - TZ=Asia/Bangkok
    restart: always
  # ---- caddy ----
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.oracle:/etc/caddy/Caddyfile:ro
      - /opt/caddy/data:/data
      - caddy_data:/data
volumes:
  caddy_data:
