kind: StatefulSet
name: wallabag-postgres
replicaCount: 1
containers:
  - name: postgres
    repository: postgres
    tag: 18.3
    port: 5432
    livenessProbeScheme: tcp
    envFrom:
      - secretRef:
          name: wallabag-postgres
    volumeMounts:
      - name: wallabag-data
        mountPath: /var/lib/postgresql
volumes:
  - name: wallabag-data
    hostPath:
      path: /opt/wallabag/db
service:
  port: 5432
