HF_TOKEN: ENC[AES256_GCM,data:jR8ht9Mq3jdy/az4c7rLbTfAcflD9fJk3VB9BmKh1k/A8/x0gA==,iv:0L2f9Knk5kVj2hXdl2jQwLCQG+kxojBKMiBWaZJEpUs=,tag:MJqgHbRad70iu1tlSp8/wg==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbXlucFcyT1lNR1Y2aW50
        MzlSS29HUVZ2YWorTnUwbWlkTWgzajJXU1U0CkNTZVBySlNXc3hKQnUwb1FxUWZI
        ai90S1FCSDR1WVNDSGcyRXBZNVk5S1EKLS0tIEd3SVRLV2RBMXllSTAwbWxUaWov
        VmVFWmJJSTZLVmpxMnpqOEdFcjNPa2cKVdWMSnvUGgJi3KubfPedQiBPHvEEyBER
        JbDMMSE8Lj8tX6XLtvzpo6MlZPGefSiwzaPY9YT/+K86nrc93vYf5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T13:32:44Z"
  mac: ENC[AES256_GCM,data:kwuzS6G39rmFS1/jPhn0YiqlVRUp8AUfVj+T0EncROjs34IJxXvBZ3wjzhmog57iqGeABV8KfbTeI3stHFfto8fVOBuMLgf/cMGuzSwqbC8ObMH72Gsl/T2MJeYNhhwqoS5TYbMsXZF+W055qE3glJ0CnD8QjbqF0Re/YeA0gjw=,iv:/wr9HvwWc8X1NEV85q3KLgi6JgSKFtpAEATVZH5vMzk=,tag:fgyT2V6owLHHRIiy+H0ODg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
