---
kind: Deployment
name: go
replicaCount: 1

containers:
  - name: go
    repository: harbor.karnwong.me/api-load-test/api-load-test-go
    tag: "latest"
    port: 3000
service:
  port: 3000
  nodePort: 30001

# helm upgrade --install go base/chart --values go.yaml