---
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: ${JWT_SECRET}
      AUTHELIA_SESSION_SECRET_FILE: ${SESSION_SECRET}
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: ${STORAGE_PASSWORD}
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: ${STORAGE_ENCRYPTION_KEY}
    volumes:
      - '/opt/authelia/config:/config'
    ports:
      - 9091:9091
