---
theme: ENC[AES256_GCM,data:rEVyJSY=,iv:09otGmvkHcLD38gqPFD8W1XGP5N33hGQtPjctV8Nfl4=,tag:PDJSkPMkoDfOFgAU3nVXfQ==,type:str]
identity_validation:
  reset_password:
    jwt_secret: 
      ENC[AES256_GCM,data:+JuDcNLn5VjqgGXqGbK9qNNPPB0B3DUe05+NgmIYymKxuqyY48eRXLjto5u6y/+Eoj4kLRtcz8P84cREUrYwpg==,iv:ELm5PiR4X9fN0ouF2z7K8GHWsb7IUfcr96CRFegIg4E=,tag:5u/jz26sD2BpNfUxGtMHKQ==,type:str]
server:
  address: ENC[AES256_GCM,data:X7/Uoh0rWvEt4AlXJDvhxBF8Hg==,iv:8rWGeoEDjfF5/bC32DYqz9lvqqAzdRwyLJ+HQc5H+gw=,tag:NDvo9cuHQ7whPV0fYR4xLg==,type:str]
log:
  level: ENC[AES256_GCM,data:5I2iyw==,iv:fC5X7dA8uawry8DrmonI63l8Bvxtf/UgOV0TB3VjU5U=,tag:e5VRXOprmK2G2oCHDhpWdw==,type:str]
totp:
  issuer: ENC[AES256_GCM,data:SqlGJvrhhtADSJY=,iv:JJaHXyss1tycQmTF9c8knAjVil49UlvWDE+AkZcEKK4=,tag:u3sq/6NFUMH1zhL/xAJSbw==,type:str]
  period: ENC[AES256_GCM,data:Ux8=,iv:FfmTqfEyc1Dqs8cc5cKiaHjr3SB/sYl/XxOG+dXUOes=,tag:Pz1zcZQAj6CYvra1ZtoTeA==,type:int]
  skew: ENC[AES256_GCM,data:cw==,iv:MRJjT5k9ZcwzQbCkgHacIoOu+OGZgKhT5ir4k51VyWw=,tag:gtxBF0flknY1gPdEdywWJw==,type:int]
authentication_backend:
  password_reset:
    disable: ENC[AES256_GCM,data:vVHrZ+I=,iv:XT6Lckl7zgXGTxuvikSuRfbC0tiAae9GiHNK7ANdnmo=,tag:DCZH6mxuKakhX3DXx8EOUg==,type:bool]
  refresh_interval: ENC[AES256_GCM,data:JJY=,iv:KqO9K243W/Hadel+ucFq8iI3dAUIM54TaP0w+eB2oL4=,tag:0n34A/k3eFRmy5vobqL73g==,type:str]
  file:
    path: ENC[AES256_GCM,data:ByjhpOVRDsqDsFfwa++fOSY//6L4St0WQbw=,iv:2acXlLtXjkMlP7kAqmoHvubaQDbshtR1Yx06J5tTBQ8=,tag:WAB+wszFaoO3mCK8iIrGiA==,type:str]
    password:
      algorithm: ENC[AES256_GCM,data:034ZcWTg6E4=,iv:f7rdZsej9w39qYeIpy9DiDcuf67I+I7W7dAhQ0rU/L4=,tag:XEN35j+HhaXlTywz6Td5sQ==,type:str]
      iterations: ENC[AES256_GCM,data:qw==,iv:58SpP9GoTHnXhtwYEpTXudqB0hZL2BzQh1Md/NhmKkk=,tag:FHWghfqYYaugqL1yKL/RPA==,type:int]
      key_length: ENC[AES256_GCM,data:Aig=,iv:z+hcQVvIRRH2BA6iVUX3oXrLV+YtpogY2SmJtdqbwCE=,tag:63qD1QT4BKtSXyht+pbNEA==,type:int]
      salt_length: ENC[AES256_GCM,data:Y6k=,iv:LqJfOECl86J4ETxCIldZQ42nFoPfp7lNcA6xIjBgT38=,tag:TgFBC7nwrQ9tTyMSH7PoYw==,type:int]
      memory: ENC[AES256_GCM,data:nhEppA==,iv:0FHsNLUQwLvwDr5xYCXAoTFNK4QWU41bEmbOSutQ0pw=,tag:MVBGfo3v8q4MjVXouhbuRQ==,type:int]
      parallelism: ENC[AES256_GCM,data:SQ==,iv:HiNqQn/IUrJEqsxYsN8YA6R1xTiREi72DQ5++J6giB8=,tag:7qTjR/CizAeWhSrjzvV81A==,type:int]
access_control:
  default_policy: ENC[AES256_GCM,data:VRD4qQ==,iv:9EYDz+en118CFUV1NMxdMSZmurXqGxmJoNBXeRSE018=,tag:XiH6L0v7foCMqPvwB+i00Q==,type:str]
  rules:
    - domain:
        - ENC[AES256_GCM,data:MnM7Ll/efAJt7hq1JsjlYw==,iv:XnFbwyvR+ln0GUSSZlG1POQsTdrdv32RthbPIfLZ71U=,tag:38fTAhe/4ApJrIxpyztUsg==,type:str]
      policy: ENC[AES256_GCM,data:Euvna2ip,iv:JkPlQXyiEdj2mTaWgy2SYt6HYeOZcPd+rc5M2L92lMY=,tag:kcsnLKF+qHORqICFBtMoHA==,type:str]
    - domain:
        - ENC[AES256_GCM,data:DAdE07MBL4Da2VbK3l/pNw==,iv:Vp80CIYAZgNoJWLM27Zefm+yzHqE0n3hVcApzIaLe1k=,tag:BGkEqB9zTQcQ9RM54bPz7A==,type:str]
      policy: ENC[AES256_GCM,data:D5FAu49tUjV1vw==,iv:WY92/MmIrfCB3wEpl2Zt2n7wjpOle9MUlXYU6WYw9z4=,tag:ORGi2rqqXoRopOg7C2OBgg==,type:str]
session:
  name: ENC[AES256_GCM,data:r/HEPEiOMHlENiqfkJ3R3g==,iv:SX2EgGzaH9jw+oR2lnFhB4zoJLK10AHAelzTeI8JjRY=,tag:1s4/FA2rpbuoFfp28Lt0WQ==,type:str]
  same_site: ENC[AES256_GCM,data:QEy5,iv:cfOCcB/h4o/0Cip5ewfqH4XKqGPrXXpG8VIwsIqjne0=,tag:FeyWJJOFqSLKozXT5yVGsw==,type:str]
  secret: 
    ENC[AES256_GCM,data:7eKYY0HW8KGqGWs7E+r5CwY9sTZ92jVS/XEpQincg8Y9FDjWNJNkknnapWWL,iv:5W2ID5g+/bam6r0DVXL1snID8twZUESgdVxxcbeSkgk=,tag:M2DrWqsbHgJUVw1OlCYHXw==,type:str]
  expiration: ENC[AES256_GCM,data:8L4=,iv:2AdtdxiifxFEumgyaoiG16XbBvMqsXrvd8uHjBeGpb8=,tag:T/XGg068THEv5LvDSVuJEQ==,type:str]
  inactivity: ENC[AES256_GCM,data:mG8=,iv:GYu10QV7y8/OV5Pljos1eQKFt7UJgI1levuOKSJy0iY=,tag:zPbgzuVWzO0mql4hYx2Qag==,type:str]
  remember_me: ENC[AES256_GCM,data:OSw=,iv:9nw4kgK04wWpFEOA6zX1esGNmwZqzVCZGCzl4UgFC/s=,tag:5QQJxi86du2TZ713GAMf5A==,type:str]
  cookies:
    - domain: ENC[AES256_GCM,data:LiRBUv8og8Xx02Q=,iv:VrkW5DUII5gcY24ytrMVcKFaAanfAj2GB3RDHH6pyX0=,tag:XwGENyoZ8REn/gA6kli/OQ==,type:str]
      authelia_url: ENC[AES256_GCM,data:DbqyktdbiL8RhSi4YztZZ0Y6dVENWN66iA==,iv:SxD36o5i7aVl3IqEqVtYjcrk98/d5lW04EGSUj8IRPI=,tag:w++Ow32sCyPV9xMdXKP74Q==,type:str]
      default_redirection_url: ENC[AES256_GCM,data:05xv4yYn5T+a8TvOPGwWIc/YF0Y=,iv:Bi9v8SddGU1lW3veWfDKKGqNrucb52iBkdvwgWkMPeY=,tag:KI+BLATj60hg0Y0hVHmn6g==,type:str]
storage:
  encryption_key: 
    ENC[AES256_GCM,data:huJc3s/JV41q3RHNGDayEPTvgxlUTxKGFmQ1lY2KwSs=,iv:KqGMeOU5GiEcSD50qkmR0hmIDzPhSgajg3tZh1VkaM4=,tag:RAet3mjyygTZ3gjrqMEGUA==,type:str]
  local:
    path: ENC[AES256_GCM,data:z1pbpVmNCopz/VJGACGiIWw4TwrUFgos,iv:aA1bNvhyWJdbhOxd+lubhVxLzI5tLUzcM7xoieJIv48=,tag:CUmFWfJOTuUMY2coMKMHGQ==,type:str]
notifier:
  disable_startup_check: ENC[AES256_GCM,data:sDJugSI=,iv:tIr4v8KXWNYJBWMHVS388u5nkKliIuqIeG2B1BFT6Qs=,tag:AToM87w1x3tOIvAWbbtuLA==,type:bool]
  filesystem:
    filename: ENC[AES256_GCM,data:4Ep2rUnNEkktpmZSNC9kbWn2hp7U8oTgpp4yQvCF,iv:/K5pUjN6/6KZgZE6WLWwQ0Fqg70iI8DLhll+qujmAQU=,tag:c8+PONj2hWmyw363FvoimQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEelhndU42UEZldWUyb0Qy
        ZFBGbzlqcTM2b3NjNWliTmcrL0F2T3VhZW00ClNqNnhKbjlaRHBlb3lrMU0vQjJZ
        NUQzTGZhOWJucU9LV3MwdkZlVGJpOU0KLS0tIGFGMkhnSVFrMHFBbWdWcFhtbTdr
        L2tkSmFVMEo0VUFXUVdQei9qUGw0WDAKvpvziUesE80L1orq7Nd5rO+oQMoYIqTO
        ZvOA7WPESr4SI1N8rjhp7AdgEZyqLtJTKj7KmRKkFU9AzPwY4iaOag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-29T14:22:28Z"
  mac: 
    ENC[AES256_GCM,data:MvmJham7YpxTdlXZfd5uAqKhNqfOqGg7nn8m8y7vZWCfJJStJbNR0Vs6OcynGwwbF2P+0wNr/Uoxflo6Z7hgr790kzpZh+/VHbnNDJU17TpvUvtqfa0DJxgt7vtrVDPWJ7qJqKO2yL1Y2Fdj00mtdvuAeDao4IT98Hr7qobWrU4=,iv:69EaK6C/K7Mi5/8ojfJpJtx3cQPMiuZy7cpuzeWZetA=,tag:MGVofxfY4A7ONIyo3ed+2g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
