---
theme: ENC[AES256_GCM,data:dyyMuB0=,iv:ZwVhRbcDIS6EA26McTccihZO2yZbu9PCwvDRiChuBNg=,tag:xYsQRJwOusV3SdJe1pATTg==,type:str]
identity_validation:
  reset_password:
    jwt_secret: 
      ENC[AES256_GCM,data:r5/InL1oAf66UiIdP150ALHhllZE0x05vrmGni4NsOo3B4nbhHOytAAw0qV2TsEPMpfz2VZue6zKq2f/t0qkVQ==,iv:e1BVHGJA1yWPmKrhTJJ15GjrAZEQ5UCQz/WrfdXjT8k=,tag:/h65LZJXq7ZCN1ifebP3CA==,type:str]
server:
  address: ENC[AES256_GCM,data:NG1yMMRyswD79vThgbGfywmCYA==,iv:AfnlVI8FddzmqUTTpuP5mfKzLab1lcXCPW065UDwfhA=,tag:6/MO0z8xocKMikALLDYRmg==,type:str]
  endpoints:
    authz:
      forward-auth:
        implementation: ENC[AES256_GCM,data:929vkT0XrZXmiMY=,iv:XSJTzs36bVuMsLQqyKMPJtVzYNMRarFKm9WJeuO/5nc=,tag:AxO/KFsHeBgeQwwoqgJ+gg==,type:str]
log:
  level: ENC[AES256_GCM,data:E54coQ==,iv:lj61AA7Vy8FXwH9u5UhRyz3CPz/8REsu4kCLb2Hj/eY=,tag:zfgY1e8nWA3uxOpdKLirCg==,type:str]
totp:
  issuer: ENC[AES256_GCM,data:g95PWhZSb6Mxlqs=,iv:lJGa7ilz9K4hpuW+61f6qTjUXfWv4JXiRpWErvOB+Yk=,tag:NU8p/syexjoHlOFz1RUc/g==,type:str]
  period: ENC[AES256_GCM,data:MoA=,iv:mwJr/0Wk3Ls0tVx8iBv8v8jHGRZ++VqxcXaWVBRkBxU=,tag:3T7Og99sGs0DbtpGfr19Lw==,type:int]
  skew: ENC[AES256_GCM,data:YA==,iv:kSLWb1vzP7FXEb2qXvfDOYdauJOM2z9y//+RH2m9w+U=,tag:rm99sn/1C4lvgNtxfxa9YA==,type:int]
authentication_backend:
  password_reset:
    disable: ENC[AES256_GCM,data:AMfzSWQ=,iv:HTGsapYNXGFkL7eZ2IWUKqbcar/VafSkrvqwyK0GjQQ=,tag:Js1iqmpFKLt1kgL8jSep7Q==,type:bool]
  refresh_interval: ENC[AES256_GCM,data:yuM=,iv:7v8zW/zXRlGoG6pOyaZNKwehE6yutBFg0x7aXBj11DE=,tag:EK7VK+sfQXOlXNvTvUfW6w==,type:str]
  file:
    path: ENC[AES256_GCM,data:V2ay9F0FkuFEVF/b2/keqRXgKm50Jp63nBE=,iv:zjE1qBb6w+kYFD5Own8QjURRRqvjLWApDv7VV+53Bng=,tag:StwWXGLDd7v07BsCtdOIXA==,type:str]
    password:
      algorithm: ENC[AES256_GCM,data:QKMMQAQz1Ik=,iv:nA411XTbSYIZLtNC18SBaON2D73vaqIB9XuifsqGN+Q=,tag:+169/Sqc3+6s7adMqgPnAg==,type:str]
      iterations: ENC[AES256_GCM,data:OA==,iv:VTLyqxdmB5n+DfjSFZ50RvaBHXGg858nlCVLBS/g9kQ=,tag:DnhXL+3EVwO5xHxfqeKUKg==,type:int]
      key_length: ENC[AES256_GCM,data:TMo=,iv:tJPnZSAlujeQF2MHyXWr1WtKsUBvHDd4lMZD6YosIxg=,tag:pp9LYu6PhLdz6XdyahEmsw==,type:int]
      salt_length: ENC[AES256_GCM,data:jbE=,iv:I4DkJtlQr4Fs/a9FqPKXcR5q2CjX7iHzeqYR+ZlEXQU=,tag:UcbNddkB3mQuteNOWTKamA==,type:int]
      memory: ENC[AES256_GCM,data:Omdv9g==,iv:xA5+K65MFieJdxYl69k/mvWHO4Ot9OTBbJ2SoDehYmE=,tag:PDOjz1rXCBD9+dCb1kZwjQ==,type:int]
      parallelism: ENC[AES256_GCM,data:ag==,iv:31qS9JRx/DnuphUV0seHaD1hwEEFNE0a3tp8fxUxiGw=,tag:fwC+hjE/6o7PUt134/WSvQ==,type:int]
access_control:
  default_policy: ENC[AES256_GCM,data:OTS2fQ==,iv:mBQQpBNxXAGQnDDySivJwnF8lbgf+NLtu0lceHs0aa8=,tag:aKn3Ebun4I5bJI4vTsS8Pg==,type:str]
  rules:
    - domain:
        - ENC[AES256_GCM,data:BzlsEz5gKNVv5Oy0Pby14g==,iv:+LCrnEJLcwVkv8jkAE8Ota/kSBlxE3d0rmL2/JvBOEc=,tag:ni2h7bJEzUIr0mjs40zePA==,type:str]
      policy: ENC[AES256_GCM,data:vVaxaGug,iv:t44A1umvkywFId7J2v//qhs3IKnnj0XZl6mF6YncSDg=,tag:bgBXJnOZmwAkKuGaH9OyUA==,type:str]
    - domain:
        - ENC[AES256_GCM,data:ReCZgZf3datLAeWDiPqWwLl4QQ==,iv:9dIMFtLRYKGIx+D1Tp9jHX5WpODUCQ/U6voK81huKkA=,tag:rJHo1GNc3ozG/LU3WGcoFQ==,type:str]
      policy: ENC[AES256_GCM,data:Kv2GbCRwwSvTWA==,iv:atnNk1ccWNPLhP3z8zIul7a1ndpCmCcDvt4X/2HHN5w=,tag:QigGOHhKG0XB1tI63GZQyw==,type:str]
session:
  name: ENC[AES256_GCM,data:E5Mmk0/yOxVz36DedwzaTQ==,iv:EzcO0r42zjWTat/dktQd0dzv6uo0V0SDtYTt+wczoBY=,tag:Wu5Km0iTrW+uoskwumgZIQ==,type:str]
  same_site: ENC[AES256_GCM,data:7pY2,iv:cTtqQ27a0NpwuA73xPVDFH50AFNTcTUdUdgoJMXwRLU=,tag:ULVZBK2xAWXX/Vqx9qQQFg==,type:str]
  secret: 
    ENC[AES256_GCM,data:ynTtwrSxMN3IlaYyedzfEqt1ckczy3oNK5WVTOGZoLssUcwxwEbZ9xegIOI/,iv:p6OuJ8SpmtoikbkkkQq+Us67qdbkJ+JA+Lt0N8dIk4o=,tag:qacSatr4SMZSu0gzRXbbzg==,type:str]
  expiration: ENC[AES256_GCM,data:k1w=,iv:Oj8zhCC1dyDZGfO2esYmgLR14xdUPu5d2aebGhtCv4I=,tag:YdJbzgepAB4w/ATJiKrrQQ==,type:str]
  inactivity: ENC[AES256_GCM,data:5Z4=,iv:kO5HwyDaohx9gXJmXS8JJH7Kve/849+4Q5qlf+wzCyo=,tag:JSD+QUJofxGWaOzOKfIWkA==,type:str]
  remember_me: ENC[AES256_GCM,data:Z0k=,iv:ZE2uNR3fdg1D72lQDZOO/QT+/D4gFq6blSrpJ/sxO4A=,tag:6ihaTZ5ERTkwcgLG9gpq4Q==,type:str]
  cookies:
    - domain: ENC[AES256_GCM,data:xH5kUkwRy6WDKBY=,iv:2xGRymw64C8UM/zURknagcXjn1HltO4rlD5CDVpi02s=,tag:WGqiYLnRS44vje7cgn3Npg==,type:str]
      authelia_url: ENC[AES256_GCM,data:sTlAZyfuBZ9dwJCj9hUnTmibU3gV8Bvnrg==,iv:KBAzZHGd52uZp+P6/ccTOKxLhG1JmZD3jpPSDQrcZdk=,tag:5yErYbw57fiWmG7GxItK0Q==,type:str]
      default_redirection_url: ENC[AES256_GCM,data:jLqRfldtGqNiNKfuuaupcMTZ0nU=,iv:W4Ep166rB2CHA+ZTw5Bd+lRMj/7jLAs9v/gWFH8qKOA=,tag:VELueXXrKTqIlC1h8IWGUA==,type:str]
storage:
  encryption_key: 
    ENC[AES256_GCM,data:UvG8zLONWotqHCPOB/3eMdVkSI3Bsj5MWcp6ZH+cIlA=,iv:rxueVh9BCh1hRReBegDJzefNEC49do4o2EXBIqCt7DE=,tag:d3rFMBM0jOVDtjWa8mlh5w==,type:str]
  local:
    path: ENC[AES256_GCM,data:rRrWJZDMcWSnMrmZqRrvQEoO4pLsSm+3,iv:D88yk17nzBpQ770VYuh0V9d6aHXeoWT4m6thf+hjFY8=,tag:exVUcrGps2JKNpfkGXZtqw==,type:str]
notifier:
  disable_startup_check: ENC[AES256_GCM,data:iMxv//o=,iv:quhEzCWc+KiYMcMFkd2xmZxFRTcmNy7UrtSEy9djOCU=,tag:Fh3onZZw4FYDJpKfco+pmQ==,type:bool]
  filesystem:
    filename: ENC[AES256_GCM,data:WHDi1W+AGSdtpJ0AOJxs3RQeEowXMVddoUzS0Bnt,iv:WNI0yDtacpA5WKjh9eOiToICwz1Sf6L5gQ9OMhDZnLw=,tag:Brmo6tTVx6kAU5HebeMPwA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZUd2VFNDdlB5NnVUeTRU
        dDdHSXlqeGw4MllWYUo1Z1RiMlBZSzk1VTJ3CklCcW5hcVg0NGFDZGUralFTdm9s
        NVYySE9XaEo0WGZrT29VUzUwb3plbnMKLS0tIHdLb05sWVcwMG5Pc3o5dmhYY3FZ
        aTZjRE11cjhnRDIwbnpQeHZkOTNGMmcKo7FJwBocSWSgE0u1Poht8ohsDccz6rit
        OqkI1a03BiaNAVWIVwRIMNX6CQA8v6PBTPfmITXf9zBTraBCkSYy9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-29T14:51:18Z"
  mac: 
    ENC[AES256_GCM,data:93QeJXtSSbB9ZuUQeZwlBuUVx4x7ufP6ZwHbW5ulADYpOoXFUQTQdc7Nx8Rg3wF4bR2hhM0HsbBchJRwRklJwXteRxQ/KeQrt2pID2ECNEV/WZ2RfqFICQvxphXamCis2LBfTxgdsZfXpFdsG9av5+4rxZoJ6yhbicFqE7OiakU=,iv:mOOmCFYXMBfQTXCFKliNdk+Rky5f+orfPuzI8mR0W1U=,tag:P4oI/KM44egf4KmD+x/frg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
