---
apiVersion: v1
kind: Service
metadata:
  name: greenkube
  namespace: greenkube
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: greenkube
  ports:
    - port: 8000
      nodePort: 30067
