AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:bK9SyI3CDKScjURyBz9ngcd7ezPy,iv:XIigxr3bwfOABS01Z9rHUsVArRzR47MVWzBo+Le2LFM=,tag:VszLVaKsACwpD24vvcE0RQ==,type:str]
AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:5ypRtINb6jnEctJNGKd9,iv:bZOIjW78lxfBpi+8qxFnwl8hlYVWUADwh/QVkbD1Pg4=,tag:bA4gHNjfHCYk5IgsAIfQNg==,type:str]
AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:phWIDcAmO8ff+mTDeUPGXicxJjEC3JP3+NOjCPa2lomzEMLP,iv:aPUcoWhndgseXQxB5Lg1EGlD2P1xFvVnMhws7L3Imrw=,tag:UOYvww/utXzChyS2ieivmw==,type:str]
AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:fszd,iv:kFiqRGmNE+//DXv6Ut13Mdpg6c0Osp4Qsv+j3A1LC2Q=,tag:pxbOLrFZ5N0PIR15MxhZzQ==,type:str]
AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:Ou4=,iv:TYhJ4IcV/sjC1hdqV3aQKKl84r4iMOa6ZP+nLERsogs=,tag:HXB8Eago07VhUaEbUZLPUw==,type:str]
AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:grA2Da2n,iv:Ufh62Z4Q1lNHyPgik2CNimyPrbakRIJEx7VMMIBgZJo=,tag:hyOm9KByjp/j5fTWpYldMQ==,type:str]
AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:lInirj8=,iv:3QD9ix5YFX5ur8ogL8IvEwi+22qp8xb17KWLOAJYAnc=,tag:FIli+nnVHuOqm5jIIpAgpQ==,type:str]
AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:75WLXg==,iv:dPn9paiPkF0SFqODazZvK4xBKf7FNcm1TlQIM4y4sX8=,tag:0QeJrdq5wtmgsRIhvgVWnw==,type:str]
AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:oep8Vt3sjNYI+gj0LHVrmuwl1Y2rmhqcgZjSxpnCn6hLV7SiXJAzyQPlB/KBFatvNS+k3mnT,iv:KlS4FMPhE+sz+xUrEyXCbyDZBu+uzcP9cXAOhhFgOTU=,tag:0TJ3H/rHEaSrKgpG/aeT4Q==,type:str]
AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:14ibZ71ElocI+cg3C2amY704AWCU9H7g3ACzgU5P5gA=,iv:+1wtEeNLXwLkFXvuqTe+1xroyKDszcDMTe9HU1Lr2zk=,tag:/n2zv2FdRcPCpmYZW5R5qw==,type:str]
AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:wP5c6oS05yG5d3iUKWDFJsIxlqjZ0ffEGCSXttxYAnlqyq6WVymzlLSV2Ds=,iv:JxLI48T+arecmZzfnIr58fnvWEg4RAaF73z0PfgJPjw=,tag:RUaz39tJesCtwyz07SusxQ==,type:str]
AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6Nk0yNZgPTd8LQ/0Q2ddDmXIrJYNHyao3TglpwEl5H0ed2fqQ6XdYGuaBoZt0Agr7gc=,iv:ftxoB9R8ASRkG+Fq6DJNLf2hmpFbNWPORsoKjOeKuZk=,tag:AL9yPsmJiCcWUlmy0/772w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQkZON0g4blR6UEpSSHJr
            QTEyMzRtbGdaMDJWRy95ZTcxQ2U1UDhUS3hVCnN6UDI3M0o2dFhtOXMzcjlCSzYx
            OHlwbmYzRGxjT1hiNlRvbDVpVmZNTG8KLS0tIGc2OGtGb091MlI5UDBUdENVWTJl
            cXo2V2NMcmpsQlVvVnVETHZQOEltR1UKsk6/HrZnlAmPGrnQWiynQ2HuFrzliTOW
            3DeFZhSmaAg45My0Exm2/OVVFz+e5L+MFROAE2K+cPlhIOXaWGjdNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-07-12T05:51:07Z"
    mac: ENC[AES256_GCM,data:1zHDYEheyOYtwO6WtVb11AeNd+LimD6dugC6ApNum3Uerl8yJ3jqe9f9p9dzUc+tWC9mhZz0BBmF0OdMZq9nFYlchOl+bt/MFZ4bTnlRWjZRF9l1rVOtVi9Fss9mEp/mEbE7sc5xToQWbaqZDSfsNd/ai769z6QIBbUJtLSHo+0=,iv:xmnR0gNHFvFP/CKHApF8q8CI18OtOKAXYB8bp7AZ/NQ=,tag:u0EwR3/LdA8I+kufuO6JVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
