username: ENC[AES256_GCM,data:8CxPlonKDKMU,iv:J9V0x7SXDi65wupP6CDpvEFqLo7kDjhwyVYLewnTdWc=,tag:ZgkptORm8WNxYFBVbw/DVg==,type:str]
password: ENC[AES256_GCM,data:W7drTtGXXeI+H5uaCpFFhkM8r1py69E9TaMb2rGEG5c=,iv:JxO1MaPFEvjZ/ZHFWtz2MJck7AIwvyKU6ssy9M+mqZs=,tag:+Z591Alu113ynO3ZQVs8kQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmt2aHlwU3YwcURsSGl5
        SG1uek10QlFiMFZmRFJubkdqT1B0QU1TekJ3CkJmb3I5WUppOTEvb1hoSUpsUlZq
        Rkloc2pNSitybVZrZExVSFdycExIcWcKLS0tIE1nSVhWNWFiTUZzOXh5MGlTOFd5
        bVNlQzNlYUpiNDc1RDFhcXc1N09LcTAKu8J/+XManXl0vrwcSXUm8WWFk1D6pwiD
        ampWsLlMxeR2GEGyEP+LSE/D9dytzhk9ghEOJQch/mrra3JAeWr/KQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-07-12T04:28:02Z"
  mac: ENC[AES256_GCM,data:1P/rNGxq72wq1pUMMuvGs7oghi+Z+J3Y1RpUvavhBmFTVkPRM4zeHzllrB8skGwHVxuuNTCVjIx0bii3+OUxD7Zzk8zMcR6Q4wiVTeiDWWZoBwEiZ1xfMMGSR3l2Meeigb4zcmHbTQo8kJyBT0IybmICTK5ZzlkZcQvYagCZ+tA=,iv:ow2XbhHE7rMGTgO5mgE0hskhzK71SZPb8aO5xjNA39Y=,tag:eO8vcLhIzyEZPFHJkXyl/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
