username: ENC[AES256_GCM,data:d1wgdFc=,iv:pncIgwYWzOBRy8AEyNc/aQH/Nf0QySY+Sxy3LlQKfKI=,tag:l+qMkTin8XtxiEcKg9uUUA==,type:str]
password: ENC[AES256_GCM,data:TCKWHwbgtEUKWz38Vcap9xpIDNL3u5Fjoyd8G5Q6EXM=,iv:mNr6scP0zF6WVgcfv6b+u8HwCODjXgUnguNP+oPIegY=,tag:KxoB5fnImAyYqDYV3bsCdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUGRudnN4K3l4V2c1c0ZB
        SXZhTDBXbm14YmhlRUtzMlVqRStWNVZsUVRBCnQvMXAwVjlUMWwwQS9nZldSNENB
        ajd6YWJJaElldk0vSUlrY044d002N2cKLS0tIExkTElMRHVqZjF1M0p1VkVWMGNj
        SVhRVnZQY2F0bWUrckRoMHYvWlMwSTgKy+KiQHC/Io4LfxbGjR6c7XHWop6b6X42
        zH6xOQbTSsT70qVZlyOZ1VG1MjiVYSuDHmp2zpTIJz8YQvaCaZfidQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-05-31T08:02:47Z"
  mac: ENC[AES256_GCM,data:KiFnO+jGk2/T9RB/INht5eTnSH6ZD1jdtFvHtDSz4q5IS9XasVJrbfCNSvMSTxSOlAcKbIysyEztC0x2tZlJJpB1n08hmK/Hb1P47N7SnkEDeu/21UWWY2J/cB5xAtKCgn5iNtNCy0YCjSPHu+ktO7ykYzEk4RqPvZDDUirS/6s=,iv:Ld9NuFtkU0QAEYlkIOzl22fqiG9GDRZeGlgOj17tYFo=,tag:5Usm0305Z9wp2KRYoa5eFA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
