ENCRYPTION_KEY: ENC[AES256_GCM,data:J52POUekAEC25FTjqnfFoDlsY+tENfTKUqBGQJVttPoSFLwpkjjw0pXB5rY1IcrQRp2tjSrtGEQ3+UzCqgHo/g==,iv:0rgWM4Wg5KMcPfKAiEr33QfRw7seEBJBpTneHG7yXFc=,tag:EFhbjtOXTFTC3xSCH9RzeQ==,type:str]
HOST_BIND: ENC[AES256_GCM,data:2Uk2O7uDFw==,iv:kOzMaGV0NlM9jVTz2mjdbpValISMZs8MqHMW5oPyLvk=,tag:qkDh6WcY3QH73ucmlCjZWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpem1EZzh2bGlSQ2orcXh2
        TTZrdzVydGJVN2k0S0JjRmg3WlZ5QS9jSG1ZCkRFY01Lb0ViUEYyRVROUmRodlVr
        N2RlZEVDREF1Rjh5RzBBUFNqdVNkU0kKLS0tIDhKQWVHbksrNCtoTCtTUmZYN1pt
        cWlKbzdzQkRYdDQyZlFLWmpxRWxNdUEK+AgF0+3axOqim657vhHpyDH8DoXG09WY
        u4Ycc4j8MR/eqXrW8bep7npMwlXu0u2hPeRb7m16rY9tEWDAIC0sgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-09-04T06:54:55Z"
  mac: ENC[AES256_GCM,data:PE4I9Wy+3B8z7Lzfu2Hsy/fD2D+BrBrnfWd5oeCDXaPUu/6r+pmhHFb5VM/c8P/KaBixs3aWj2/3fKPiLPoRRnaUP+9JzCBy22+6XkaTRt5iiiOrMexliCHQwBibUISyMVS704BtS7xXbl53r1S7h3WJbQinBejlq8Nl79MDgfY=,iv:/eKKd3Tzdugm/OwUTm6NSmzSD8d81ALzBVrbRZEEFxY=,tag:h3JXzZTFoAFLpsQQKvXqpQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
