username: ENC[AES256_GCM,data:GqUIqOAp,iv:Wv17Q49o/UvpARtbI8rFpPivIU0Q7xef9tePnZl8VJ4=,tag:L/XJbRewDVrXPY3StHKcWQ==,type:str]
password: ENC[AES256_GCM,data:mDhYivWIRsqgCHPf7YtYLu/MWBOgLsDa5wGbU6uVZYz6G3NTOCF47/i9uYq9G9Aaq/U5qJdSLZsvwNGTgMtoaw==,iv:LuiPVnNpqpk5x2cAuNepwz7EVJz902NnAox6GvWQR8g=,tag:IRUbFIyYCS3wKobBRPN5oA==,type:str]
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmt2aHlwU3YwcURsSGl5
            SG1uek10QlFiMFZmRFJubkdqT1B0QU1TekJ3CkJmb3I5WUppOTEvb1hoSUpsUlZq
            Rkloc2pNSitybVZrZExVSFdycExIcWcKLS0tIE1nSVhWNWFiTUZzOXh5MGlTOFd5
            bVNlQzNlYUpiNDc1RDFhcXc1N09LcTAKu8J/+XManXl0vrwcSXUm8WWFk1D6pwiD
            ampWsLlMxeR2GEGyEP+LSE/D9dytzhk9ghEOJQch/mrra3JAeWr/KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T09:11:48Z"
    mac: ENC[AES256_GCM,data:NMAmjNC8Hkirmoc/2ZaAXCO50xh3o6tMw9UHXO9aOpYwtZt+4fLAF2mlHZrOXVDQD7fulrpDMSf7DVyV20nEgQWnqEtA0Cpiqo9pUzVLKDsLJ3EESkahlzexsmJKQnCpwTVnkbaHC8kCJ+7aghnGHPcv7hTwf6setZXXIWzTQEg=,iv:MDpWggFVM47mEAuUIuVcnW1gVDE60z+Wy5AwCeBv8Wk=,tag:58gy1vDTvQw1fOY4tqg+ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
