username: ENC[AES256_GCM,data:kzkaG6sK,iv:XSJCctdI4xtarzgNEEB/vep2KDsrCfSo11HNG+gvtFE=,tag:vEpZU4JOuOfWudn4bwA9cg==,type:str]
password: ENC[AES256_GCM,data:P3sceZyN6d7//LFC/mVzlMxrEM4gqWyM2SIbs2Wtfp8=,iv:h7CYhsogmyDDjX1MTwlGa7h2HHHESGGE9RZn2ylfSEs=,tag:0NzqEiMUe36rBWjAvtAowg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHFvWmJ3NWVHQ0JZaDh0
            bVhMc3ArSW9aVzE5L3hJRlN0M1MxOEFNRFY4Ckpsb2R4cG02OHl5NmNzNVJLQWpw
            a3EvaGxDa1hHK1lMbEpFUmlTMEJMNEEKLS0tIGpkSWNSUzhacWk1YUpKenVzdm5F
            d0ZaaHl3d25GWEtkMm5zS093MCtxQmcKMCLRNmO+94LwIEbn2UUPnrPrdSfPQAOM
            epiZufTAhAdhQxZJ4IZ9q7EPeWx4fIJdSUXIt7aoGkQ4MOPCFgX6vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-07-12T07:15:00Z"
    mac: ENC[AES256_GCM,data:D++IGO0KyU3mlk8i3RuYgHlc+QPRlx49ZLJvwdtNb+Knbvc2y6juj+V6BeuNWxTUNVIAB0hS0mRFYHwaC7C6bsCCQ34dDBZ+GqfeX2EArWpz+9q3j617FG4Ma0ErkE5Gv4tz/6e5vApIclnUN0QriW3esou+M2f0vXepSB7YMtM=,iv:wOyMKvhtsEAQzUrp+TbM9oVYrHnNryNXh0f0vHfLYz4=,tag:1igx9Ib1hgNeqOywu3m45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
