username: ENC[AES256_GCM,data:C3gBra39oGY=,iv:J8zKlAPPnuD2Ta+XPkpuDKHdg2Vs6yOb21rsuYk/PqA=,tag:7FaWnB1XT2FLe+12w09pvw==,type:str]
password: ENC[AES256_GCM,data:iBkG/V54oH4l2Yqf/hBpfMKHsRfpbNTtJAyYjxlH6sbV5pCt6yCcqTCNcldDBQ==,iv:kXCdQ0rlnEIeup0Kw5OKj1inygkm5KVDmsIPIO0Caw8=,tag:lPCCLnBMnFCHiGrMbD1jPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHFvWmJ3NWVHQ0JZaDh0
        bVhMc3ArSW9aVzE5L3hJRlN0M1MxOEFNRFY4Ckpsb2R4cG02OHl5NmNzNVJLQWpw
        a3EvaGxDa1hHK1lMbEpFUmlTMEJMNEEKLS0tIGpkSWNSUzhacWk1YUpKenVzdm5F
        d0ZaaHl3d25GWEtkMm5zS093MCtxQmcKMCLRNmO+94LwIEbn2UUPnrPrdSfPQAOM
        epiZufTAhAdhQxZJ4IZ9q7EPeWx4fIJdSUXIt7aoGkQ4MOPCFgX6vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-07-12T08:31:02Z"
  mac: ENC[AES256_GCM,data:YUjJLEsgLmDoTPRGIaCrGO8s8jHWh/vWFsDwiYD6RKwEUMmv+2PRYjko7aoF4d3g/iMeKcP7QsEKD8UWJChK4kxZhbpVNAqCuGNtKbsZ2jsPgusRwEoEO0RgfVyHIyNV/h+4dHFlixAd7ttX3csxaR57EEgIUa/XeoZ3lyPzOr8=,iv:n2rEWJhUbWm3XKLX16InhabFTIaJc2Bvz3cFYbyH2H8=,tag:MxpbhmOqsFME9sHdsp0tWg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
