POSTGRES_PASSWORD: ENC[AES256_GCM,data:97NC8cEzR9PYNF+70IMIKTktwGR6KprxqFBmJmwVTnXE5JT3uJOUfC8+Q3mVAg==,iv:DGYphlKo6ufLXv+4+k01Ln4reniN9ex31NbnjmwcC8Y=,tag:cyOaqfu2/+YpTlIZEa4FHg==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:VGlKAD2JSxM=,iv:SBu8vqPMWB+3HJ4TRrsjJ9EQLRrYwcZ0EAMW2hA3uNg=,tag:RB8IykGUmPW1Y75uXeyTTQ==,type:str]
SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:Ywa9Vgvs,iv:tZZIgsdvf+8fdO1+VBMngMxhPvbCUINGtCUF/Typ8DY=,tag:vz0a74aniEzjtFd4Yw9EDA==,type:str]
SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:6kRAsIEKRUcjDvEaPpemQkMnqHvOwe9McrC74P4uDc4QNEliO4M9f0ZKuUUcCZ8=,iv:feExP5AtlysMJgJceg9wqyHl782fPo64j/Vi24WKM7E=,tag:6LsSjJvi5QN+xUIddBSxgA==,type:str]
SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:op4j9g==,iv:DQeNt21eg0qn8GjeYpNq4Nocon2yFO+X+Ye9oNriarU=,tag:lrLaGe68jwUUH9rpoeyA0w==,type:str]
SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:F/sD8tq+Ebo=,iv:cUw3ImfmALBHdfGeUJfsIO/8PNFszT4d7ac6fBILpgs=,tag:nXVxRekQNE4zR97OiGqEhA==,type:str]
SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:hLykTNESecw=,iv:RiZ0TdMpTvKKE0gyndQ3FTADowXEdGDZDi87iSjiS8Y=,tag:OlL3vyJiPrPMiMp6Oj3HCQ==,type:str]
SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:Z0671oIrDiJO2rV63sf7JF4bSqw+jLI7GksBAfGy5L6ffnaNCNWi0Ipnx2KNxw==,iv:JugDBaKpgl5rhIVpjYGWKxJdwZOQnfNCbZBhgaLaVsE=,tag:3bYOCMZlp3ejzJXNRYRIVw==,type:str]
SYMFONY__ENV__REDIS_HOST: ENC[AES256_GCM,data:PCjt9WDiV95CpG8aJ1GDkjg9Nvp7vMy6JoMQQJi/4obPJzTLXKI7YiQ=,iv:OXI6m5wAs9tz7rESKC3HnSY0r2XPhVbUVZZhAA2NqZ4=,tag:CXJuxCmdcf2msDJKOBxX4w==,type:str]
SYMFONY__ENV__REDIS_PASSWORD: null
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTjI4dk9WMWtQMU5LeWZn
        cEFnNGRYc3AxYjBNY0lvQjd3K0ErUGRBK0J3CnVPZllTZ2V2K1BCQnN2RjdYTVp6
        TmVML1B2WWNGUkR6aERzSzNMaDFhc0kKLS0tIDVyYk95VHEwWmNyYitMbUluVUh3
        cDhITGExUHZaVnpsNG1LTHl2QXVrZm8Km64RUXznMC4qoVb1KJ1Ynie/we//zmKq
        cvozkwKLpgzKCnBdYyx6uZJBO4OcAOrokxde8GujzBkAPdnuoWCO/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-07-12T08:30:00Z"
  mac: ENC[AES256_GCM,data:85MTgumCEqfL4K+Q46JsCZxm8AKqtpilrRAGVssVGs1zAv7jyZG/kL/APnKNFyHn3AJAWOkQVIL9m6PIK7M1gL/RG3BxTrdJ+CafyrYiG2WhvHALqh+Ee9Mhn+5tIyN2YgxOl2on8FdET9pagaHofB324oSKthgqVc+SUPJR8vc=,iv:ofBQCXp31IulJwUkT2Rg4R/fpmOI6AlDtC9dkG2UMKE=,tag:HVO6XjcWJ0kwtm3Yu6MS7g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
