name: backup-forgejo-db
schedule: "2 0 * * *"
containers:
  - name: backup-forgejo-db
    repository: ghcr.io/kahnwong/docker-aws-backup
    tag: f09a8ec
    env:
      - name: MODE
        value: DB_POSTGRES
      - name: SERVICE_NAME
        value: forgejo-db
      - name: POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: forgejo-postgres
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: forgejo-postgres
            key: password
      - name: POSTGRES_HOSTNAME
        value: forgejo-postgres-rw.infrastructure.svc.cluster.local
    envFrom:
      - secretRef:
          name: backup
