name: ddns
# will be run via cron, but this is kept here so it's easier to trigger and read logs
# "*/5 * * * *" - every 5 minutes
schedule: "0 0 * * 0" # every week
containers:
  - name: ddns
    repository: favonia/cloudflare-ddns
    tag: 1.15.1
    env:
      - name: UPDATE_CRON
        value: "@once"
    envFrom:
      - secretRef:
          name: ddns
