FORGEJO__database__HOST: ENC[AES256_GCM,data:yMuW4RCYuri+W4ayovQcySXo79x/Yb6GEJCJa1pnARiwBYIABAGoX1OJLsKThPnZecTpDKRN1R32,iv:Q8OnVGKf2IoO+I+oqb/Uj75T+W+to5iW0Qo6mheV+fI=,tag:kW1v19KmCG17uZZyIGKHqA==,type:str]
FORGEJO__database__NAME: ENC[AES256_GCM,data:3jFdLHQ=,iv:W3kJpT0YJwmdwEp7nBz3u+yUejrZdcMIOhDMZRthtEk=,tag:ZRgPBqiSlNZfyP4wuZBs4g==,type:str]
FORGEJO__database__USER: ENC[AES256_GCM,data:s3mADRQ=,iv:p/PVI1x9FsusIwwwppwvnJuClT3jsYJwo6PWnwGU2DE=,tag:6pKB4wSQPG2r5/3i75EWxw==,type:str]
FORGEJO__database__PASSWD: ENC[AES256_GCM,data:tfeqkPZEMLqoil4sz9UABtAAy+1MR2Ps5zYwWyK1jtg=,iv:YpznNJtUm9p2FwtNV1S3VNtnJoAwUK/T52jPITqRppI=,tag:7da6HAzhk2DO9ysZ26Em9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVF3eXhaeUlYL3VxTjVK
        Q1V0YWlFUndLbzlrdDRMc3Q2KzU4eXEwbkFRCkgvb1g1cWZJMGxKREllMjdDc1Ra
        ZzJTSk1maWE2QmhkbGsxekVNNFhadGMKLS0tIFBPQ3BWcWVqT1BwbmJLSnplTVYy
        SDdSd2FFWGVJdWpCQ3cvUTUxb0dFdW8KEHWzFIOmMrWeWQMvGE+mVgIqjG0fjJuP
        IOuhU23WQgXPXrpntZR2hX39natLJd/PApar0xZhfwYXZUUGz8qnag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-05-31T08:03:14Z"
  mac: ENC[AES256_GCM,data:uC6h9U2kTuwNUxTX5ypSjmRTCqAfG/qv5ELAzQC2BoFYP57nsKg66O1BUufa+TTX+OuL87pXTseui7tn2mnR6MKu1i0ukRNIa/APTNqJXpT0u8DF/HNdhQb103XnU+0ZYf/6ahmVo5DXZl2gsiQ44p3MN/taab6TMJey8DAK7xc=,iv:sr9pxkDliUhgjBFxgPZVg7ifaZVcz9HvttUjiYSG9C0=,tag:zZ9t2j2u0aJzOxjVu2eM6w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
