username: ENC[AES256_GCM,data:Hfd1vTOC,iv:dEELL7G8PrZyHe64CwYjkniMhP23tpNRacrcBQKALXY=,tag:062Pd2hOdyRu8tsqCY0A5Q==,type:str]
password: ENC[AES256_GCM,data:zb2czAkGE+fA44pwNShrdA6oaYru5aIeopnJ1UuerAxNTIA=,iv:p5iNLd17SH/fKszqwFiL/hneyMWiayzBuEtjkVfn21g=,tag:aduENKpWCFjYSfO5VTKdhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQUFoLzlkcjFxdnFPMEE4
            UUJWb3BURWxPc1oyZm1JOG9GUUFPZ1VVTTNVClV5cFErTjZTMDgwaU9ScTBaVTho
            ZWZQQStZcFpXL0NYK2pwWXM4Mm9QTDgKLS0tIElwWjJHdmJUZytmaWl2ZGtXS24y
            N3VSbmozQWdzckZrdUNBVWxjc3QySUkKaD2hN3EkJRnkZp0ZnJBht3z325K16KPK
            J8pnjF4Jf64f9/nBbIjXJwTeazpizw3S3HDCuSYByRh1pJVh4IhIwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-07-12T09:08:56Z"
    mac: ENC[AES256_GCM,data:ovMz3y+Zn7fzFFcLpdFgRSBbmF3v2wnJP+4D/9J4sC7JbriFuYFHawjJyFbGmQ0C8WPD+tjIuOH8Bp4p8UGCqf2J1U7krrJoznvG3E5QpwlEOg1IS1yYHpgxEO5NZHTnE6p5KP3Y/D3I3QsATAuvIpKtzuk2Bhs4fqdOHPJI1Vw=,iv:2NudtKjyV9+A56Kqb0QYXdiMneubpjtmiqTeKLa/BRI=,tag:s9nqp5N8Rs00K+22ps9Fcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
