username: ENC[AES256_GCM,data:auek60X8FWI=,iv:WuvP5SCQpZoR3oIFRnSipddi+R3MaSgk6Y2VOmbXQtM=,tag:+rvv4eHyfFBOPvY+gbWtgQ==,type:str]
password: ENC[AES256_GCM,data:6i6teqOaExMPkXGcw+MnU8C5l938g+iNGTY9NHMhazE=,iv:TQC1r/s5Iv+/k98vH0y9OppAIGFm6NpUz/eo9Os6o4g=,tag:CDsEQVP6NIRqtGT9P8hnuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd1BicVluR0RpYkJETTNX
            bElMV2RoeWZzc3hMVjMxRXNrWHgyeVdUQUd3ClEvUzM5ZUh6SWpRNU1WMGpaZ1ls
            TFcyUWVpS1VlVmY3aEdmYWJYS1lyb0kKLS0tIHFWdStrcmQrZTFEUGxZZjAxa0RX
            dXZ2NXBjNUUrSTEwYndnVmhxMzJnS2MKZrKuBuBZLaN8XRpPlEpLmgHyjoceYNrf
            R+n2uPAD78bMrnZXit6uaLwYydl6XohOyu6z6HkmWjbI1WcV26mrzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-07-12T08:20:21Z"
    mac: ENC[AES256_GCM,data:d0hnvMJuLuXEZBocwSBHssz4wU/mOmATSw0Vdf/V+DW5HweVISs68XfYDaC3iuUeRMcEk2oaF5GVmRKA4+tJXHD8nPk18f1YNrWoSQlqZ3y1Q7IunB9iLS+x0Ix60QYVDzJYjcWDvVBpuvFppL/1bEQP+AuYmHIGHk38HaMvoWI=,iv:6vZ3kl+vSGFqBqX0vn/PTQsC2wXTUc6G/HMMR6m/EBw=,tag:KO6YCXtT33EBnghFDB3kiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
