username: ENC[AES256_GCM,data:3fs9bW0f,iv:miSTUgZq1Av+HXqZHM3+ZscjWNDZPYxWnZ7SFWoZJ0E=,tag:zMULNzazhnIlhVc7qLSsag==,type:str]
password: ENC[AES256_GCM,data:H3gX4csvMze4azGat5y9wGY5PsgL1tg8u/VFqvK0acI=,iv:ebU+6DZ1VhpquwwfoNEDDDtSmV/yHJaf6XSye67hZpU=,tag:glkqfyB7IvAcr9nPj/My0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOTBRbEZMY1V0VitZSG1p
            UVI4S1NyamVscElYSG9aRWNoVU1xSWtvUkZzCmJSdGh1RmJaRzNjUEZSUHdFNE41
            VEw2RmFNN2M4WHViSDd3SjJjT1BDdzAKLS0tIEV4SVhCZmt3dkpudFV3Y2N3c1ph
            c3RvNW9FMytRRklGUmdmbVlXWFpiNnMKKaTyy9Wh+uANNzgSnSsvMoaYZw0Z+mQs
            QI8AwmTYnPV+YT7lafGoKlE5uZC5kOl0IauoDMdiFRpmMbIXaCaz+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-05-31T07:35:43Z"
    mac: ENC[AES256_GCM,data:e2U35bcPE5ypLZp7lchlquQ6ZfZUyQXLc7MHYMauvrJCDb9QjjU1XNX2NcBxkO7xc7Nj3gMbjgMvniZ/ilutx3tpfku1r0RMoa/iv1g1qtt0ewUKz9bB2+OTwFAKqE/iigLr00Oai37K7R4YJgevrTFYTUzrsswr8vh4vYFsIEk=,iv:A3Gfz2w6YzHY30WA8A55/hKPBKfQAnSPvWpCAvMcm/k=,tag:uhovy66YllPpmu/ozGCW8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
