GITSYNC_USERNAME: ENC[AES256_GCM,data:j6rCNcDC1Hw=,iv:f0dYi9bqzp48W8M5stqHJnalX4wL4wDogE9tocuwjhk=,tag:qPnkFJdQh+W4JjuiebM2xg==,type:str]
GITSYNC_PASSWORD: ENC[AES256_GCM,data:hAtnhpSUz+EE9ExzJh6gd5PczFpcBqqZglcY3mSfpzImWKq4lUvOpn77oxI+Fa1GH9Qk8PxGPgkKsaShYJ7Nrb0SYIS9UypRrEC9lhfbqW2Hc9vyP311cds5YS18,iv:J1wsfaWTMWbfcGVpijiY4TTgv7wtdWjluGOTjvMxcKU=,tag:7+SWUkhRYM+FfBu0pqGSfQ==,type:str]
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0tVZ2ZCR3FERDJYOGt2
            Z1BzS0RXaW9yOWpNZWo2anZIU2t6OTgrNlZRCmVJMUMreGQwQWxJZUcxRkMwWGkw
            eW9BWWR2VjJ4bE1nTnc5b1RYTnNuTlEKLS0tIDNGdzNwTjdJL0NLRWZyOVVqL2pK
            bFYvQkVkemRSdmhKSnAvcFQ3eEx6dXcKMMPrgzDdNbUBj0h0J9W4T3tbBEuIP1cx
            EGnzO1bKoiD4AceQeIwbbdgZCITDrcXKeJjTUC4b3hJfMhA7meMCOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T09:04:52Z"
    mac: ENC[AES256_GCM,data:9YG4VMgFMQnmF7BDr1AcxGyZvvUynJsLNFQ2IJAtNX1kvWhdSPK2mNsAVhRiyyDDRsTdgoD00pxoQdqHWZJqwJat2EfpdXgkWoB+NM3IM60KNF1/tSgSsxoMNDdPeBYlGJkAMBgHnm7Qxczzp6LthtvkKUyRU5JkJH9gA8RMg/o=,iv:n/EuB/xTpjmTGwwcaMEr0jt5/Gu/o3D7Dwk7DbRaPwU=,tag:UYRTqloRSvQRj0V7d4dGZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
