OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:7nBX7BHlldIA,iv:93K8+uGOCpV1m2dLTQY4TrhmIibfqDNkqum2bnFXGNc=,tag:y6/cY1SqTHP9jN0ac4KGWA==,type:str]
OG_OIDC_CLIENT_KEY: ENC[AES256_GCM,data:2yIG28oXrtGAKo8zUmI5YjvRDgOx+y8lfz9n5Z63BZ1/LAXQxxkGSg==,iv:IPtB0wtJ/rHxmQsPBSJunzhj/ll2QlDWE/p1saMLafo=,tag:5DH9KZE35d4qUMBvPkU1AA==,type:str]
OG_OIDC_SECRET: ENC[AES256_GCM,data:wuuxo1PfaCUEzG4cb+8EC8lXYgkXx720JP17UoGsAR2rd+QgRCMAvoxRKCmZ3H5qkxPyzcXE00uSsry4KfrX8I/4roD2EKiW45iWiOldcTozuGMYfCaOkKgxMZOlBKlCqarSdBCG8BIvE6jyh4HYa0/m+Ez80yAQy4wiuBaHCVg=,iv:iMxAS5DNgQQvVjC+aA5h9mzyxgyjJaDvxp7sBoyCCkA=,tag:is6CKPiVWOTWs81+JzcwGg==,type:str]
OG_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:O7M0FvScXTi7WXfUIzlQ+++JmDZyZNLuQeF+sSBwx2lpz+QwqiDhVgGdjwfPwW3bg2JyoRXLdyJ/UmpYXmFmabJVNbpCSJRz7es7FXPIWr/7k8jjhA==,iv:Tpn4QnqAis22NKy7FrLRz3Cmf9ekLSZiaFhVaWPtJUc=,tag:X9YSkQpVnPflm/y6b/H1og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ0UxMjlBK3lWNEl5cUt3
            KytDOU9DSE1YNGlPdk1IdlphbUwxRG9aTXpnCkt2MmhJQkxNWVFRUUU4NDRRa1hr
            bE8xRW84L0RUNUpvd2l2R3Y0bW85SDgKLS0tIFNza3FjeVNVelZBaEVGeEJ6Y3lj
            WW5uQzc4YmMyWVRHVWdmRk5peVlVTDQKxZJjH4AV6hnbxCQ5maUFzferDMkAkZ7P
            NyjjbBzmuSFeSL6EI7tFfkJamZmg1h8feAcBXaGWc+7YZqqDguEeNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-08-05T09:38:08Z"
    mac: ENC[AES256_GCM,data:lnLuHgDwHjyEM85f7PE6Tavz55m1nbfixlC9+lYK+5Z135RWc7gdWL7pqSS/4EDP6jQe1rvVUJ4tp0YCa2t8Uf9IeBlLHkGsTI1ijrA1105TXdZcIuxRYXUu5MkMgmq2hmtH17K+FMP1HGsNLZlK8Ar0WWDry6Pw1Ul/mkUl+Ac=,iv:OfGB2GbzL5wmglel5qVVEmBXkKXau4o1buXB285UgxQ=,tag:L+ilnncEQqRM/rtJmmx3Iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
