username: ENC[AES256_GCM,data:UX9g71kp,iv:SPSKOcc7Y+nlLMlggeGw1HaYqcuF4Ej+8DK2jaZWNSU=,tag:IS0sWCsx0B6vLSoeU42kIA==,type:str]
password: ENC[AES256_GCM,data:6DN362I+harFeLN0ooBZyw==,iv:XsPK+YJDgAg69lfEypuXgVZrzRhsDrPhdoRYNvH5Lnw=,tag:MZsKy64ZYzd0wpp3dOnwZA==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bEV1bXppT3FPLzQ4Nm9J
        SGFqcUE0NEFKZGVBcDJDSkFpbFEvNVAzcml3Ck51d1RGQWJOR1BBME9JQkVrZmxX
        Y2d0dkdBdEZaWmpxalMvaUY4ZTM5RGMKLS0tIGpBSWJCRnJiZlBuVjZ6WU1YNzlB
        SGRNM2JTN1I4NWNxbnU0R0laNjhiMVkKWLWyThvXIizwZ8KDUwMNh2kmJOG4spqg
        GoJ/qTbMwArcQThlksxfdLQvM6tIECNrV+AbeFFmjzVsEGZH0qK/Cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T13:09:57Z"
  mac: ENC[AES256_GCM,data:/KUXp6e2C0OO1KJ0xXH7fLLYUBAHqGGefvQGMZEdqYMd5LavqL8vaMLzo3JaSZdlpEgOfvuJ8XWYEOOFCjWtWSIsCwLv8oQ8tnj3gh7qjBohWc+ROqbDIsPXNRvRSFnta4pmZA0ncMeiiqeWTA+FipvfkkVTdngK3iL5awJd2Ok=,iv:roSFG1etQAGaB+EJE+5n/pN9wL/oSrJqIPjciUM9Pxk=,tag:tF9OydR5ussHmhEKObDSiw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
