username: ENC[AES256_GCM,data:slj82A==,iv:NpTYm4q0JhNi+WB/sT5nHBGUhwJ0Ewq2pu6fiFe1lEA=,tag:/PTpdEnN32tgFXWGyehPBw==,type:str]
password: ENC[AES256_GCM,data:2rKwQ62A0b4=,iv:lisOxX3y0uBY5miFslHQBzJHPXylzDteueTHVdwDtBA=,tag:IUlwhNksb/SVi3tgkoL+TQ==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bEV1bXppT3FPLzQ4Nm9J
        SGFqcUE0NEFKZGVBcDJDSkFpbFEvNVAzcml3Ck51d1RGQWJOR1BBME9JQkVrZmxX
        Y2d0dkdBdEZaWmpxalMvaUY4ZTM5RGMKLS0tIGpBSWJCRnJiZlBuVjZ6WU1YNzlB
        SGRNM2JTN1I4NWNxbnU0R0laNjhiMVkKWLWyThvXIizwZ8KDUwMNh2kmJOG4spqg
        GoJ/qTbMwArcQThlksxfdLQvM6tIECNrV+AbeFFmjzVsEGZH0qK/Cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T10:42:43Z"
  mac: ENC[AES256_GCM,data:JvYa6FG7rnrDt3NZ3m802hIDU9MWIHHPwxLnTAHUO5mT39BjxLQIAqwUItD35bFc/eH41L6J0ATh/GuIpk1ujVBEWsWFI3Aru5ueXOcQ9O5ezMmzkv12H/IegklbWOJoAi3+pUCF4B32QmDEEJVuQYCUsDWINlU6O7tlJx5a8oU=,iv:uJR9gznR0XPWPvZuY/K6y3ELesXXWv6ZVFgVhTre6Lc=,tag:bn7L3xHDJ6EbaqkxlHBxpg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
