ENCRYPTION_KEY: ENC[AES256_GCM,data:gUX2+pNDkpRxNjvTSElYI4VyDYlP6vc7C8R6EY3DaGZPl+xt5kmlaVM76jltCmED8QU+q5iGBldPw898HEMX4g==,iv:+1Zog+S3uBXFOhCk5cUvttDXqkGByFUQ7yL7/jq6GpU=,tag:SpZuYzSnrqnx12IKPouFpQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM25aWTc4MVluaHV0OXVP
        ZHlSWGlKNlRSRUNWUmRHSWIxYnFwMjR0WVZNCnhLTmlFSnN5c0F6cUZqbWFHbko0
        OXFBK3pXK1VLZ2QwVVlBUWd1cWtTa3cKLS0tIHE4djBmeEFPbWFLTTVyUnpkcDJT
        YkVlU0tyaUJQdW5ZMnc4RHBEQm9wWk0K6TCHqpJf0SEQ9VGLXenaAGliy6LSF6cp
        Gfb0u/ggCYObXjrAdc1eGv98AzQLy+AXwZ8sdYUFiY/FS9vJWx54mg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
  lastmodified: "2026-06-04T09:01:51Z"
  mac: ENC[AES256_GCM,data:0AfnWX3ImoLfJSPGpVUbC0tTxmsFKjo2KQjYh6ft5cRrGLSXUkJNNlyVCxxzKp/xrkiTuQTCKnRIM/K4Te6ZIeyFAvCv59Za6PQQBAgiX8O7zcGm+Q/ABdxXkxhw+KE8Mb5GYG72p8v9DMRmyrE1F5AnJbuJ2zcWN0gjSyKkEG0=,iv:tNq6Iuofbq88NfAkjqmVSBBN2s62a41Qtww2QV7LfI8=,tag:TQ6gMPjdhGpFef+GhYvpxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
