APP_SECRET: ENC[AES256_GCM,data:ARAmlX+UGz6piwoywwskAuj3E/4yWKIJ+iSzOrM2knwQh2lToaPjnZqWVea2+WtH4FD1v91n8YXW+Bo/hMTLSQ==,iv:ytSMDqNp9livTvp78M0SPPV0/NLWv2jJqiYheKQSL/k=,tag:wUXx4k1d8b4nYmXOBmBLuQ==,type:str]
BESZEL_URL: ENC[AES256_GCM,data:btu4coUguTuhUEsBFITMtvuYD6qMzSUVNYE=,iv:CxzhgowbuQP/xajKeqwxcYdRQOGk+ZMthC/58HDcfmE=,tag:V1F97/bMSg++6AOvMcFb3Q==,type:str]
BESZEL_EMAIL: ENC[AES256_GCM,data:eri13cF2ySQ6QcPSuU32Ug==,iv:6/2AraubPWA4psbjSfT7ibcBweYMv+9iQMR9XfFXmnU=,tag:uBdegm4fONSxEH1eLomCuQ==,type:str]
BESZEL_PASSWORD: ENC[AES256_GCM,data:pV1cKpF9ZX35Bc9KqYH06hN3edPTlqshRVPBfJGmTYPCAyWelmJmZT4dQk+BFs0=,iv:bw8VRzSPaKRKL3o+iXJA9A5c7/PdV45baBXELxfZMJY=,tag:RAEKphMcf2V+UIriTzNkVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiODZ0OWpDdXVWbGY4Mi9K
            KzYva3EyQWtScENNb2tyakZhVHBSNEhuSmdnCkFEQXZhd3pFWUNnZ1NuSlVVUDRy
            NjRPZFFqTC91Z2R2OUlZcmExeE1ZVnMKLS0tIFBsR2loSGZPK1pKbWd2NFdvbWFi
            eERFTVh4MW5UN2RhbWJKY0lZUTdJcUUKplwIpBDGL/wCnmC41pMI4MeJ//05Fcxh
            9AUN9SHfoFwm6ApxST6eBoFK2Qrqc0eCSY1kIck2MSkyKqM9qQjPEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
    lastmodified: "2026-06-10T12:59:33Z"
    mac: ENC[AES256_GCM,data:alV3VLxjZzsHtpKKSqK0BxIl8hTtdK8nKlpIuVaKmYeRCAYbEJK/3e/F6qPQAg31yT3GwBABkw00BMBTYEhUxpdEcCS83RoGYeIIV1CTq+jvFMNRrV5gXCf625T4DUseqlgDITbeatweRNWGoH5MWGt13p/jFr9qm1/uMCs/LaI=,iv:n2kD+pXZqea+8Bsfk6UzCn3wxB1smRKJlRm/IsrFg8U=,tag:chRy6BtTst1rwyuMEcNl3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
