POSTGRES_USER: ENC[AES256_GCM,data:s4A00Og6RR4=,iv:+aB2gtN9Km2jdfkjkwHxRUazeVl/764VRTVeyx2Kqt8=,tag:F9MdKqkZH7vstQ8S1VAN8Q==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:CjpDjEuXXB+5YrnlMK1TPpGxatkot2keO+P8zvCWUwSMPnq/bMNL/X1UMxw/Fg==,iv:gMdudK0GGu4QjTJvJvbUvdOfFKCruWd2YVrjX+uMKrk=,tag:2Dl6aTwKFiNx63exTUnn8w==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHFvWmJ3NWVHQ0JZaDh0
        bVhMc3ArSW9aVzE5L3hJRlN0M1MxOEFNRFY4Ckpsb2R4cG02OHl5NmNzNVJLQWpw
        a3EvaGxDa1hHK1lMbEpFUmlTMEJMNEEKLS0tIGpkSWNSUzhacWk1YUpKenVzdm5F
        d0ZaaHl3d25GWEtkMm5zS093MCtxQmcKMCLRNmO+94LwIEbn2UUPnrPrdSfPQAOM
        epiZufTAhAdhQxZJ4IZ9q7EPeWx4fIJdSUXIt7aoGkQ4MOPCFgX6vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T05:56:18Z"
  mac: ENC[AES256_GCM,data:Guif3GsXTxHKmBN2QlRrQVCD0h3iHBq1hpaujETjF5WwA3cAao7aP6AJ3Vo4KBICpTD8Bu/ZqP/fRHNyAvXAcwWlVaunMfyv3slN+0pek8hI1gLMwheiwsTuN6kK+ywMKccwf0I4JneL3W4Iul77uk7nLprRRyZ8ibxO5h/jKq8=,iv:wvObmXa8j9TOUmV4gfYVf6utnR41p6N4UQy+XvQ9OYc=,tag:GlAO47zjaLJp8uJP5Iwkyg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
