kind: Deployment
name: sandbox
serviceAccount: sa-sandbox
replicaCount: 1
kubeGreen: true
containers:
  - name: sandbox
    repository: ghcr.io/kahnwong/sandbox
    tag: "1ead6cd"
    port: 3000
    env:
      - name: SANDBOX_IMAGE
        value: "python:3.14-slim"
service:
  port: 3000
  nodePort: 30087
imagePullSecrets:
  - name: ghcr-cfg
