name: 01-2-lunch-order
# 11:00 AM Asia/Bangkok
schedule: 0 4 * * *
containers:
  - name: 01-2-lunch-order
    repository: ghcr.io/kahnwong/line-notify
    tag: 9c70e69
    args:
      - notify
      - สั่งข้าวเที่ยง อย่าลืมปักหมุดเป็นที่บ้าน
    envFrom:
      - secretRef:
          name: family-alerts
